// web-components-with-web-frameworks/react-web-components-poc/src/App.jsx
import { useState } from "react";

import image from "./assets/book.jpg";

import "../../web-components/counter-wc";
import "../../web-components/book-cover";
import WcWrapper from "./WcWrapper";

function App() {
  const [increment, setIncrement] = useState(1);
  const [color, setColor] = useState("red");

  return (
    <div>
      <div className="increment-container">
        <button onClick={() => setIncrement(1)}>Increment by 1</button>
        <button onClick={() => setIncrement(2)}>Increment by 2</button>
      </div>

      <select value={color} onChange={(e) => setColor(e.target.value)}>
        <option value="red">Red</option>
        <option value="green">Green</option>
        <option value="blue">Blue</option>
      </select>

      <WcWrapper wcTag="counter-wc" increment={increment} color={color} />

      <WcWrapper wcTag="book-cover" url={image} />
    </div>
  );
}

export default App;

// web-components-with-web-frameworks/svelte-web-components-poc/src/App.svelte
<script>
  import '../../web-components/hello-world'
  import '../../web-components/counter-wc'

  let color = "red";
  let increment = 1;

  function incrementByOne() {
    increment = 1;
  }

  function incrementByTwo() {
    increment = 2;
  }
</script>

<main>
  <hello-world></hello-world>

  <button on:click="{incrementByOne}">Increment by 1</button>
  <button on:click="{incrementByTwo}">Increment by 2</button>

  <select bind:value={color}>
    <option value="red">Red</option>
    <option value="green">Green</option>
    <option value="blue">Blue</option>
  </select>

  <counter-wc color={color} increment={increment}></counter-wc>
</main>
